#!/bin/sh

# usage:
# merge-mozilla-history <1> <2>
# both <1> and <2> are sqlite3 databases. <1> is modified.

# bugs:
# 1. moz_places(disabled,typed,frecency,last_visit_date) and moz_historyvisits(visit_type,session) are arbitarily assigned with magic numbers.
# 2. moz_places(favicon_id) have no value thus favicon is not shown.
# 3. moz_places(url) collisions are silently ignored.

# todo:
# 1. error handling.
# 2. test on different firefox versions.

offset=`sqlite3 $1 "select max(id) from moz_historyvisits;"`

sqlite3 $1 << EOF
attach "$2" as db2;

insert or ignore into moz_places(url,title,visit_count,hidden,typed,frecency,last_visit_date) select url,title,1,0,1,1,1 from db2.moz_places;

create view db2.v1 as select db2.moz_places.url, db2.moz_historyvisits.id, db2.moz_historyvisits.from_visit, db2.moz_historyvisits.visit_date
 from db2.moz_places inner join db2.moz_historyvisits
 where db2.moz_places.id=db2.moz_historyvisits.place_id;

create table t1(id integer, place_id integer, url longvarchar, from_visit integer, visit_date integer);
insert into t1(place_id,id,from_visit,visit_date)
 select moz_places.id, db2.v1.id, db2.v1.from_visit, db2.v1.visit_date
 from moz_places inner join db2.v1
 where moz_places.url=db2.v1.url;
insert into moz_historyvisits(place_id,id,from_visit,visit_date,visit_type,session) select place_id, id+"$offset", from_visit+"$offset", visit_date, 2, 0 from t1;

drop view db2.v1;
drop table t1;
EOF
