#!/bin/sh

# SYNOPSIS:
# merge-firefox-history <db1> <db2>
# 
# DESCRIPTION:
# <db1>  and  <db2>  are  sqlite3  databases,  usually  located  as
# "places.sqlite".  many records from <db2> are appended to  <db1>.
# <db1>  IS TO BE MODIFIED. Make back‐up before use. <db2> is read-
# only.  Layout of the firefox places database is described in
# https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Database

offset=`sqlite3 $1 "select max(id) from moz_historyvisits;"`

sqlite3 $1 << EOF
attach "$2" as db2;

insert or ignore into moz_places(url,title,visit_count,hidden,typed,frecency,last_visit_date) select url,title,1,hidden,typed,1,last_visit_date from db2.moz_places;

create view db2.v1 as select db2.moz_places.url, db2.moz_historyvisits.id, db2.moz_historyvisits.from_visit, db2.moz_historyvisits.visit_date, db2.moz_historyvisits.visit_type
 from db2.moz_places inner join db2.moz_historyvisits
 where db2.moz_places.id=db2.moz_historyvisits.place_id;

create table t1(id integer, place_id integer, url longvarchar, from_visit integer, visit_date integer, visit_type integer);
insert into t1(place_id,id,from_visit,visit_date,visit_type)
 select moz_places.id, db2.v1.id, db2.v1.from_visit, db2.v1.visit_date, db2.v1.visit_type
 from moz_places inner join db2.v1
 where moz_places.url=db2.v1.url;
insert into moz_historyvisits(place_id,id,from_visit,visit_date,visit_type,session) select place_id, id+"$offset", from_visit+"$offset", visit_date, visit_type, 0 from t1;

drop view db2.v1;
drop table t1;
EOF
